# Generated by Django 3.1.7 on 2023-02-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banknote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
        ),
    ]
