# Generated by Django 3.1.7 on 2023-02-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banknotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banknote',
            name='pick',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banknote',
            name='day',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='length',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='month',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='width',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
