# Generated by Django 3.1.7 on 2023-02-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banknotes', '0002_auto_20230213_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='banknote',
            name='currency',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banknote',
            name='intro_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='banknote',
            name='intro_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='banknote',
            name='intro_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
