# Generated by Django 3.1.7 on 2023-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banknotes', '0004_auto_20230218_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='banknote',
            name='composition',
            field=models.CharField(choices=[('paper', 'Paper'), ('polymer', 'Polymer'), ('hybrid substrate', 'Hybrid substrate')], default='paper', max_length=20),
        ),
        migrations.AddField(
            model_name='banknote',
            name='issuing_authority',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
