# Generated by Django 3.1.7 on 2023-02-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banknotes', '0005_auto_20230218_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='banknote',
            name='acquire_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banknote',
            name='acquire_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banknote',
            name='acquire_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banknote',
            name='grade',
            field=models.CharField(choices=[('unc', 'UNC'), ('au', 'AU'), ('xf', 'XF'), ('vf', 'VF'), ('f', 'F'), ('vg', 'VG'), ('g', 'G')], default='unc', max_length=5),
        ),
        migrations.AddField(
            model_name='banknote',
            name='printer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
